### ISSUE TITLE
Strange error msgs

### ISSUE THREAD

**Issue by jud3bl4nk** [jud3bl4nk/javascript-less-carousel#1]
Hi @mackenzierose,
So I'm honestly not sure how to describe this problem, as I don't fully understand the error messages I'm getting from markbot (the msgs are in my last commit).
From my perspective, it seems as though there is a div which should wrap around  my li/labels but that line of code is not in follow along for this assignment  (https://learn-the-web.algonquindesign.ca/courses/web-dev-4/javascript-less-carousel/).
I'm also getting an error msg saying I'm missing a 3rd child (again, seemingly in my li/labels), but based on the follow along I don't see where that error is.
Hopefully this description helps... plz let me know if I can clarify any further.
Thanks in advance,
Jude

**Comment by MacKenzieRose** [comment]
Hey @jud3bl4nk!

Fantastic explanation. 

You've done 99.99999% of everything perfectly; this error is a case of mis-typing a class.

If you go to line 35 of your index file, you'll see you've written "carousel-control" instead of "carousel-controls"; pluralize that baby, and you should be good to go. :) 

MacKenzie

**Comment by jud3bl4nk** [comment]
Thank you!
